---
- name: Обновление apt
  apt:
    update_cache: yes

- name: Установка зависимостей (Java)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Создание nexus пользователя
  user:
    name: nexus
    shell: /bin/bash
    create_home: yes

- name: Скачивание Nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/nexus-3.79.1-04-linux-x86_64.tar.gz
    dest: /opt/nexus.tar.gz
    mode: '0644'

- name: Распаковка Nexus
  unarchive:
    src: /opt/nexus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Переименование директории
  command: mv /opt/nexus-3* /opt/nexus
  args:
    creates: /opt/nexus

- name: Назначение прав доступа
  file:
    path: /opt/{{ item }}
    owner: nexus
    group: nexus
    recurse: yes
  loop:
    - nexus
    - sonatype-work

- name: Изменение конфигурации nexus.rc
  lineinfile:
    path: /opt/nexus/bin/nexus.rc
    line: 'run_as_user="nexus"'
    create: yes

- name: Создание systemd сервиса
  copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=nexus service
      After=network.target

      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart=/opt/nexus/bin/nexus start
      ExecStop=/opt/nexus/bin/nexus stop
      User=nexus
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target
  notify: Перезапуск nexus

- name: Включение и запуск nexus
  systemd:
    name: nexus
    enabled: yes
    state: started

