---
- name: Скачиваем Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Установка Helm
  shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

