---
# handlers file for ansible-role-vault

- name: Ensure vault service restarted
  systemd:
    name: vault
    state: restarted
    enabled: true
  listen: restart vault
  
- name: Ensure vault service reloaded
  systemd:
    name: vault
    state: reloaded
    enabled: true
  listen: reload vault

- name: Ensure firewalld service reloaded
  systemd:
    name: firewalld
    state: reloaded
  listen: reload firewalld

- name: reload systemd
  systemd:
    daemon_reload: yes
