- name: Обновление пакетов
  apt:
    update_cache: yes
    upgrade: yes

- name: Установка необходимых пакетов
  apt:
    name:
      - git
      - python3-dev
      - python3-pip
      - build-essential
      - libffi-dev
      - libssl-dev
      - python3-venv
    state: present

- name: Создание пользователя stack
  user:
    name: "{{ openstack_user }}"
    shell: /bin/bash
    home: "/opt/stack"
    create_home: yes

- name: Разрешение sudo без пароля для stack
  copy:
    dest: "/etc/sudoers.d/{{ openstack_user }}"
    content: "{{ openstack_user }} ALL=(ALL) NOPASSWD: ALL"

