---
# handlers file for ansible-role-vault-agent

- name: Ensure vault service restarted
  ansible.builtin.systemd:
    name: vault
    state: restarted
    enabled: true
    daemon_reload: true
  listen: restart vault
  when: vault_enabled
  
- name: Ensure vault service reloaded
  ansible.builtin.systemd:
    name: vault
    state: reloaded
    enabled: true
  listen: reload vault
  when: vault_enabled

- name: Ensure firewalld service reloaded
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  listen: reload firewalld

- name: reload systemd
  systemd:
    daemon_reload: yes
